### ISSUE TITLE
how to cmake your code with arm

### ISSUE THREAD

**Issue by tsingjinyun** [fastfastball/dlib_for_arm#1]
thanks for your great work, and how to compile with __ARM_NEON parameter with cmake?

**Comment by swim010** [comment]
@fastfastball thanks a lot for your work. I have the same quetion as @tsingjinyun . Can you help us?

**Comment by tsingjinyun** [comment]
@zoumzl set(CMAKE_CXX_FLAGS	"${CMAKE_CXX_FLAGS}   -march=armv7 -mfpu=neon -std=c++0x" )

**Comment by mflor35** [comment]
@truedat101 It is worth noting that `armv7` is unsupported on RasPi3 Model B. we need to use `armv7-a` another simpler way to accomplish the same is to use `-march=native` and/or `-mtune=native` but we can't use because of a bug in GCC-4.9 which is the current version on raspbian OS.
