### ISSUE TITLE
 If you use the dlib_for_arm library, What is the face detection speed of the 1080p(1920*1080) image on the arm platform?

### ISSUE THREAD

**Issue by Hardold** [fastfastball/dlib_for_arm#3]

**Comment by Hardold** [comment]
Could you give the reported speed of the face detector ,which is tested on the arm platform?And the size of tested image is 640*480 and 1920*1080. Thinks  a lot.

**Comment by fastfastball** [comment]
In Android 5.0 & Cortex-A53@1.4Ghz 4 cores platform, it takes < 70ms to do face detection in a 640X480 picture. For a 1920X1080 picture, the time consumption may be 6.75 times i.e. 70*6.75~= 500ms

If the performance is not good enough for you, there are still several methods you can try

1) if in your application you only need to detect "big faces", plz reduce 640x480(1920X1080) to smaller one(for ex: 320X240)
2) pay attention to thermal issues. Some BSP may slow down or even turn off some CPU cores if cpu temp is high enough.
3) check http://stackoverflow.com/questions/38435653/detecting-face-landmarks-points-in-android
