### ISSUE TITLE
Something about how to enable neon option?

### ISSUE THREAD

**Issue by Hardold** [fastfastball/dlib_for_arm#4]

**Comment by fastfastball** [comment]
you may check this link https://github.com/fastfastball/dlib_for_arm/issues/1
Or, if you are in Android environment, Add the following lines into your Android.mk

ifeq($(TARGET_ARCH_ABI), armeabi-v7a)
    LOCAL_ARM_MODE := arm
    LOCAL_ARM_NEON := true
endif

ifeq ($(TARGET_ARCH_ABI), arm64-v8a)
$(info Enable NEON compile option)
    LOCAL_ARM_MODE := arm
    LOCAL_ARM_NEON := true
endif

**Comment by helloearth012** [comment]
@fastfastball  Do you have Android.mk and Application.mk besides your checked in makefiles? Thank you.
