### ISSUE TITLE
I can't compile it

### ISSUE THREAD

**Issue by gicheonkang** [fastfastball/dlib_for_arm#8]
Hi, I'm making a app which detects faca landmark.
I' heard you contributed the performance of dlib.
I want to use your code, but I fail to build it. 

1. clone [https://github.com/tzutalin/dlib-android](https://github.com/tzutalin/dlib-android)
2. replace dlib repo with your dlib_for_arm (rename with dlib)
3. build with android version as described in [https://github.com/tzutalin/dlib-android](https://github.com/tzutalin/dlib-android)

But, It doesn't compile with 
`error: ./obj/local/armeabi-v7a/objs/android_dlib/jni_face_det.o: multiple definition of 'dlib::currentTimeInMilliseconds()'`

can you give some advice?
I wanna upgrade my app. Thank you for your contribution

**Comment by ithmz** [comment]
I also got the same error, did you fix it?

**Comment by Hjy20255** [comment]
> 
> 
> I also got the same error, did you fix it?

@gicheonkang @tsangz189  i got the same error ,how to deal it?
