### ISSUE TITLE
android NEON details

### ISSUE THREAD

**Issue by gicheonkang** [fastfastball/dlib_for_arm#9]
Hi, I'm testing your code in android platform.
I heard that you tested dlib with [dlib-android](https://github.com/tzutalin/dlib-android)
How did build it with NEON support?

**I need to know the details about - Application.mk, Android.mk file**
I tested, but I can't build because simd file is added.
Thank you for your contribution :)

**Comment by helloearth012** [comment]
@gicheonkang  How did you finally build with Android.mk and application.mk?  I am also working on the same platform.
